### ISSUE TITLE
Bug: sorting is a little broken

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#102]
**Describe the Bug**
discord message reference: https://discord.com/channels/1075403862124531753/1075403862556557429/1154236296189988935

**Stream Master Info**
- latest

**Link to logs (required)**
- willing to provide if needed

**Comment by SenexCrenshaw** [comment]
Should be fixed now

**Comment by aniel300** [comment]
will test and report back, thanks you.

**Comment by aniel300** [comment]
> Should be fixed now

i was able finally to test this as per "StreamPipelLine-0.3.2-StreamPipelLine.1-0026" but it still doesn't work the way am expecting it.
